"""add currency and default_budget_month to users

Revision ID: 617a357f8d12
Revises: 8800ff59edca
Create Date: 2026-09-06 10:08:35.574198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617a357f8d12'
down_revision: Union[str, Sequence[str], None] = '8800ff59edca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('currency', sa.String(length=10), server_default='KES', nullable=False))
    op.add_column('users', sa.Column('default_budget_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_budget_month')
    op.drop_column('users', 'currency')
    # ### end Alembic commands ###
